project:
  type: website

website:
  page-navigation: true
  title: "Virtual Store Feasibility Report"
  repo-url: https://github.com/NASA-IMPACT/virtual-stores-feasibility-report
  repo-actions: ['edit']
  sidebar:
    pinned: true
    align: center
    title: "Virtual Stores Feasibility Report"
    logo: graphics/nasa-logo.png
    contents:
      - href: index.qmd
        text: Home
      - href: executive-summary.qmd
        text: Executive Summary
      - section: Guidance
        contents:
          - href: recommendations.qmd
            text: Recommendations
          - href: limitations.qmd
            text: Known Limitations
          - href: governance.qmd
            text: Governance
      - section: Technical Aspects
        contents:
          - href: technical-overview.qmd
            text: Technical Overview of Virtual Stores
          - href: technical-features.qmd
            text: Technical Features
          - href: nasa-applications.qmd
            text: Virtual Stores at NASA
          - href: nasa-ecosystem.qmd
            text: Virtual Stores within the NASA Ecosystem
      - href: resources.qmd
        text: Resources, References and Presentations
      - href: contributing.qmd
        text: Contributing        

format:
  html:
    theme: nasa.scss
    toc: true
