---
title: "Technical Features"
subtitle: Additional information on technical features and their maturity levels
---

# Mature Support

**Current mature implementations share the following characteristics:**

- Virtual stores are used to provide alternate views (defined below) into the data. These views can range from an entire collection, to subsets of a collection, to a subset of a granule.
- Consistent spatial and temporal resolution across each variable (i.e. array) within a virtual store
- Uniform chunk grid and compression scheme across each variable within a virtual store
- Chunk manifests are generated for a particular view and may span many granules

::: {.callout-note}
We define the term "view" in a virtual store context to mean the different ways the same dataset can be represented. For example, a view of the same dataset could be representing the entire dataset as a cube or some a subset of the dataset, or a single variable array or a data tree of multiple groups of arrays. Different views will make sense given a datasets characteristics and the intended use cases.
:::

## Supported data formats

Data format support is limited to formats with VirtualiZarr parser implementations. Parsers maintained by VirtualiZarr include:

* [HDFParser](https://github.com/zarr-developers/VirtualiZarr/blob/main/virtualizarr/parsers/hdf/hdf.py)
* [Kerchunk (Parquet or JSON)](https://github.com/zarr-developers/VirtualiZarr/tree/main/virtualizarr/parsers/kerchunk)
* [DMRPPParser](https://github.com/zarr-developers/VirtualiZarr/blob/main/virtualizarr/parsers/dmrpp.py)
* [FITSParser](https://github.com/zarr-developers/VirtualiZarr/blob/main/virtualizarr/parsers/fits.py)
* [NetCDF3Parser](https://github.com/zarr-developers/VirtualiZarr/blob/main/virtualizarr/parsers/netcdf3.py)
* [ZarrParser](https://github.com/zarr-developers/VirtualiZarr/blob/main/virtualizarr/parsers/zarr.py)

Parsers maintained outside of VirtualiZarr include:

* [virtual-tiff](https://virtual-tiff.readthedocs.io/en/latest/)
* [hrrr-parser](https://github.com/virtual-zarr/hrrr-parser)

Custom parsers for additional formats can be implemented using the VirtualiZarr [CustomParsers](https://virtualizarr.readthedocs.io/en/stable/custom_parsers.html) guide.

# Developing Support

## Non-uniform grids

Some NASA collections present additional complexity due to having varying compression schemes and chunk grids across a logical array (usually across granules). Currently, Zarr assumes a consistent chunk shape and compression across the entire array.

However, support for both varying chunk shapes and compression schemes is in active development and should be available by summer 2026.

## Non-cubable data

COMING SOON

# No plans for support

* There are no plans to support formats outside of the "Supported data formats" list above at this time.
