name: Spellcheck

on:
  pull_request:
    branches: [main]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: codespell-project/actions-codespell@master
        with:
          skip: 'graphics/*'
          ignore_words_file: .codespellignore
